server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location /stress_tips/ {
        try_files $uri $uri/ /stress_tips/index.html;
    }

    location = / {
        return 301 /stress_tips/;
    }

    error_page 404 /stress_tips/index.html;
}
